/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author danilotavareslima
 */
public class telacalc extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telacalc.class.getName());

    /**
     * Creates new form telacalc
     */
    public telacalc() {
        initComponents();
        panCalc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNum = new javax.swing.JSpinner();
        btnCalc = new javax.swing.JButton();
        panCalc = new javax.swing.JPanel();
        lblResto = new javax.swing.JLabel();
        lblCub = new javax.swing.JLabel();
        lblRaizQuad = new javax.swing.JLabel();
        lblRaizCub = new javax.swing.JLabel();
        lblAbs = new javax.swing.JLabel();
        lblRestoResult = new javax.swing.JLabel();
        lblCubResult = new javax.swing.JLabel();
        lblRaizQuadResult = new javax.swing.JLabel();
        lblRaizCubResult = new javax.swing.JLabel();
        lblAbsResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel1.setText("Digite o valor:");

        txtNum.setModel(new javax.swing.SpinnerNumberModel(1, -50, 50, 1));

        btnCalc.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(this::btnCalcActionPerformed);

        lblResto.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblResto.setText("Resto da Divisao por 2");

        lblCub.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblCub.setText("Elevado ao cubo");

        lblRaizQuad.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblRaizQuad.setText("Raiz quadrada");

        lblRaizCub.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblRaizCub.setText("Raiz Cubica");

        lblAbs.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblAbs.setText("valor Absoluto");

        lblRestoResult.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblRestoResult.setForeground(new java.awt.Color(0, 153, 255));
        lblRestoResult.setText("0");
        lblRestoResult.setToolTipText("");

        lblCubResult.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblCubResult.setForeground(new java.awt.Color(0, 153, 255));
        lblCubResult.setText("0");
        lblCubResult.setToolTipText("");

        lblRaizQuadResult.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblRaizQuadResult.setForeground(new java.awt.Color(0, 153, 255));
        lblRaizQuadResult.setText("0");
        lblRaizQuadResult.setToolTipText("");

        lblRaizCubResult.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblRaizCubResult.setForeground(new java.awt.Color(0, 153, 255));
        lblRaizCubResult.setText("0");
        lblRaizCubResult.setToolTipText("");

        lblAbsResult.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblAbsResult.setForeground(new java.awt.Color(0, 153, 255));
        lblAbsResult.setText("0");
        lblAbsResult.setToolTipText("");

        javax.swing.GroupLayout panCalcLayout = new javax.swing.GroupLayout(panCalc);
        panCalc.setLayout(panCalcLayout);
        panCalcLayout.setHorizontalGroup(
            panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addComponent(lblResto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(lblRestoResult))
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addComponent(lblCub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCubResult))
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRaizQuad)
                            .addComponent(lblRaizCub)
                            .addComponent(lblAbs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRaizCubResult, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAbsResult, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRaizQuadResult, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panCalcLayout.setVerticalGroup(
            panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalcLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResto)
                    .addComponent(lblRestoResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCub)
                    .addComponent(lblCubResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizQuad)
                    .addComponent(lblRaizQuadResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaizCub)
                    .addComponent(lblRaizCubResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbs)
                    .addComponent(lblAbsResult))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(txtNum.getValue().toString());
        
        // Resto da divisao
        int r =  num % 2;
        lblRestoResult.setText(Integer.toString(r));
        
        // Potencia cubica
        double c = Math.pow(num,3);
        lblCubResult.setText(Double.toString(c));
        
        // Raiz quadrada
        double rq = Math.sqrt(num);
        lblRaizQuadResult.setText(String.format("%.2f", rq));
        
        // Raiz cubica
        double rc = Math.cbrt(num);
        lblRaizCubResult.setText(String.format("%.2f", rc));
        
        // Valor absoluto
        int abs = Math.abs(num);
        lblAbsResult.setText(Integer.toString(abs));
        
        panCalc.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telacalc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAbs;
    private javax.swing.JLabel lblAbsResult;
    private javax.swing.JLabel lblCub;
    private javax.swing.JLabel lblCubResult;
    private javax.swing.JLabel lblRaizCub;
    private javax.swing.JLabel lblRaizCubResult;
    private javax.swing.JLabel lblRaizQuad;
    private javax.swing.JLabel lblRaizQuadResult;
    private javax.swing.JLabel lblResto;
    private javax.swing.JLabel lblRestoResult;
    private javax.swing.JPanel panCalc;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
